### PR TITLE
Fix o2_Tags::gather_all_tags() to account for tax_input that is mutated by edit_post()

### PR DESCRIPTION
**Pull request by westonruter**
This fix a warning when trying to do Quick Edit of terms:

```
explode() expects parameter 2 to be string, array given in ...wp-content/plugins/o2/inc/tags.php on line 298
```

I believe this regression was introduced in a change made to `edit_post()` earlier this year; see https://core.trac.wordpress.org/changeset/31359

### CODE REVIEW

**Comment by westonruter** [comment]
*bump*

**Comment by swissspidy** [comment]
Thanks for the fix! Seems to work fine again when using QuickEdit, but not when bulk editing posts.

**Comment by westonruter** [comment]
@swissspidy not work in what way?

**Comment by swissspidy** [comment]
@westonruter Sorry, I should have been more clear. What I did:

1. Select some posts which all have the same tag "test"
2. Click bulk edit, already notice that the _Tags_ textarea is empty
3. Insert new tag "newtest"
4. Click "Update": "newtest" is properly sent to the server, but the posts don't have any tag attached anymore.

It's working on my other sites, so I suspect it's an O2 thing. If you can't reproduce it, I'll open a separate issue.

**Comment by lancewillett** [comment]
I'd say merge the change for Quick Edit — and create a new issue for bulk edit. Could be non-related.

**Comment by lancewillett** [comment]
Closing in favor of #13.

**Pull request closed without merging**
